return {
   "tpope/vim-fugitive",
   lazy = true,
   cmd = {
      "Git",
      "Gstatus",
      "Gedit",
      "Gsplit",
      "Gdiffsplit",
      "Gvdiffsplit",
      "Gread",
      "Gwrite",
      "Ggrep",
      "Glgrep",
      "GMove",
      "GRename",
      "GDelete",
      "GRemove",
      "GBrowse",
      "Gclog",
   },
}
