[theme]
name = "plain"
[theme.overrides]
idle_fg = "#eeeeee"

[[block]]
block = "sound"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 30

[[block]]
block = "disk_space"
path = "/home"
alias = "~"
info_type = "available"
unit = "GB"
interval = 30

[[block]]
block = "net"
device = "eth0"
graph_up = true
graph_down = true
interval = 5

[[block]]
block = "memory"
clickable = false
display_type = "memory"
format_mem = "{Mum} ({Mupi}%)"

[[block]]
block = "load"
format = "{1m} {5m}"
interval = 5

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "temperature"
collapsed = false
interval = 5
format = "{min}° {average}° {max}°"

#[[block]]
#block = "battery"
#interval = 15

[[block]]
block = "time"
interval = 5
format = "%a %b %-d %-I:%M:%S %p"
